# Generated by Django 4.1.7 on 2023-04-25 03:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppPaginas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagina',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pagina',
            name='imagen',
            field=models.ImageField(upload_to='paginas'),
        ),
    ]
